id: I80D4ED33
legacy_id: P006979
ocr_import_info:
  bdrc_scan_id: W22073
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T10:24:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T10:11:46.265213+00:00'
last_modified: 2022-08-27 18:12:58.267449
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22073
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22073
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཧོར་གླིང་གཡུལ་འགྱེད།
statistics:
  ocr_word_mean_confidence_index: 0.884021368131723
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG17892:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17892
      total_pages: 452
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17892.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.9007273296431942
    legacy_id: v001
  I1KG17893:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17893
      total_pages: 606
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG17893.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8719661157113419
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
