id: I80D4ED33
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:28:19+00:00'
last_modified: '2022-06-08T09:44:46.027643+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22073
  title: ཧོར་གླིང་གཡུལ་འགྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6372':
      image_group_id: I1KG17892
      title: Volume 1 of hor gling g.yul 'gyed
      total_pages: 452
      order: 1
      base_file: 6372.txt
    7F83:
      image_group_id: I1KG17893
      title: Volume 2 of hor gling g.yul 'gyed
      total_pages: 606
      order: 2
      base_file: 7F83.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
