id: P006979
initial_creation_type: ocr
source_metadata:
  id: bdr:W22073
  title: ཧོར་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes:
    67cfba6605764e5eb0462512ade3b456:
      image_group_id: I1KG17892
      title: ''
      volume_number: 1
      total_pages: 452
    aad0b3e4661c420480d8ad7a96312e6d:
      image_group_id: I1KG17893
      title: ''
      volume_number: 2
      total_pages: 606
ebook_metadata:
  title: ཧོར་གླིང་གཡུལ་འགྱེད།
  author: ''
  sku: P006979
  cover: cover.jpg
  layers:
  - pagination
