id: P006979
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22073
  title: ཧོར་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes:
    f498f36e76764174b40163b3659c5bb4:
      image_group_id: I1KG17892
      title: Volume 1 of hor gling g.yul 'gyed
      volume_number: 1
      total_pages: 452
      base_file: v001.txt
    73fa30e1e7994a268333f4698f56a562:
      image_group_id: I1KG17893
      title: Volume 2 of hor gling g.yul 'gyed
      volume_number: 2
      total_pages: 606
      base_file: v002.txt
